name: stochopt
channels:
  - http://conda.anaconda.org/gurobi
dependencies:
  - python=2.7
  - networkx
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - gurobipy
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
